# Chapter 4 : Activation Functions

Pg: 72 - 110

- Activation Functions are applied on the output of a neuron: Activation(input*weight)
- What they do is they modify the output of the neuron (introduce non-linearity)
- The reason we need them is the allow the hidden layers the ability to map nonlinear functions
- Hidden Layers by themselves (inputs x weights) cannot produce non-linear outputs
- Two Types of Activation Functions:
1. activation functions used in hidden layers (usually all the same)
2. activation functions used in output layers (different most times)

![linears_vs_nonlinear.png](../references/linears_vs_nonlinear.png)

## The Step Activation Functions

![step_func.png](../references/step_func.png)

- Purpose of Activation Functions is they mimic a neuron "firing" or "not firing"
- Simplest version of biological activations is the Step Function
- Fires if: weights x inputs + bias > 0 (ouptuts a 1)
- Rarely used in practice because it is not differentiable, you can't smoothly figure out how it changes (cannot compute gradients)
- Historically used in hidden layers

- Main Problem: not very informative (to optimizer), less clear to optimizer what impacts weights and biases have on the output because of the very little information from step function
- An optimizer works by assessing individual impacts that weights and biases have on a networks output
- Doesn't tell you how close you are to activating (what if you were only .00001 away from activating)

## The Linear Activation Function

![linear_func.png](../references/linear_activation.png)

- simply equation of a line
- appears as a straight line in a graph
- output always equal to input
- used in output layers for regression problems (outputs scalar values instead of a classification)

## The Sigmoid Activation Function

![sigmoid_func.png](../references/sigmoid_activation.png)

- Sigmoid is a S-shaped curve
- Sigmoid activation came after step function as a more granular and informative activation function
- Sigmoid is a smooth function, differentiable at all points
- Sigmoid squashes the output between 0 and 1
- Sigmoid is used in output layers for binary classification problems
- historically used in hidden layers
- Equation: f(x) = 1 / 1 + e^-x

Eventually Replaced by ReLU (Rectified Linear Unit)
- More challenging to compute than ReLU

## The Rectified Linear Activation Function

![relu_func.png](../references/relu_activation.png)

- if x is less than or equal to 0, then y is 0
- otherwise y is equal to x
- allows positive inputs to pass through unchanged

- Simpler than Sigmoid
- simple and yet powerful activation function
- ReLU helps preserve important information in the neural network
- most widely used activation function (at time of writing)
- reasons for popularity: speed and efficiency

Reason ReLU is Interesting:
- extremely close to being a linear activation
- remains nonlinear due to bend after 0
- introducing nonlinearity, which allows the network to learn more complex patterns and relationships

![linears_vs_nonlinear.png](../references/linears_vs_nonlinear.png)

## Why Use Activation Functions?

Linear Problems:
- very simple problems in life are linear in nature
- ex. price of some number of shirts is linearly related to the number of shirts

Nonlinear Problems:
- most problems in life are nonlinear in nature
- Main attraction of neural networks is their ability to model complex nonlinear relationships
- ex. price of a home has many factors size, location, rooms, etc. (not linearly related)
- ex. sine wave

![sine_wave.png](../references/sine_wave.png)


Neural Networking Fitting to Sine Wave without Activation Function(just linear activation):
![sine_wave_no_activation.png](../references/sine_linear.png)

Neural Netorking Fitting to Sine Wave with ReLU Activation Function:
![sine_wave_relu_activation.png](../references/sine_relu.png)

## Linear Activation in the Hidden Layers

No matter what you make the neurons weights and biases, the output of the neuron will be perfectly linear to y=x of the activation function
![linear_activation_hidden.png](../references/linear_activation_hidden.png)

## ReLU Activation in a Pair of Neurons

Pair of neurons with single inputs and ReLU activation functions, other negative weight

![relu_activation_hidden.png](../references/pair_relu.png)

## ReLU Activation in the Hidden Layers

![relu_activation_hidden.png](../references/relu_part_1.png)

![relu_activation_hidden.png](../references/relu_part_2.png)

![relu_activation_hidden.png](../references/relu_part_3.png)

## ReLU Activation Function Code

In [20]:
# 1st Implementation of ReLU
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2,-100]

output = []
for i in inputs:
    if i > 0:
        output.append(i)
    else:
        output.append(0)

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [21]:
# 2nd Implementation of ReLU

inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2,-100]

output = []
for i in inputs:
    output.append(max(0, i))

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [22]:
# 3rd Implementation of ReLU (using numpy)

import numpy as np
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2,-100]
output = np.maximum(0, inputs)
print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [23]:
# Supplemental Code Necessary to Run

import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

# Dense layer
class Layer_Dense:
    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    # Forward pass
    def forward(self, inputs):
        # Calculate output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases

# Create dataset
#X, y = spiral_data(samples=100, classes=3)

# Create Dense layer with 2 input features and 3 output values
# 2 neurons for per layer (3 layers)
#dense1 = Layer_Dense(2, 3)

# Perform a forward pass of our training data through this layer
#dense1.forward(X)

# Let's see output of the first few samples:
#print(f"Dense Weights: \n{dense1.weights[:5]}")
#print(f"Dense Biases: \n{dense1.biases[:5]}")
#print(f"Dense Outputs: \n{dense1.output[:5]}")


In [24]:
# Our Rectified Linear Activation Class

# ReLU activation
class Activation_ReLU:
    # forward pass
    def forward(self, inputs):
        # calculate output values from inputs
        self.output = np.maximum(0, inputs)

In [25]:
# create dataset
X, y = spiral_data(samples=100, classes=3)

# create dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2,3)

# create ReLU activation (used in Dense)
activation1 = Activation_ReLU()

# make a forward pass of our training data through this layer
dense1.forward(X)

# forward pass through activation function
# takes in output from previous layer
activation1.forward(dense1.output)

# lets see output of the first few samples
print(f"Output (No Activation): \n{dense1.output[:5]}")
print(f"Output (ReLU): \n{activation1.output[:5]}")

Output (No Activation): 
[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]]
Output (ReLU): 
[[0.         0.         0.        ]
 [0.         0.00011395 0.        ]
 [0.         0.00031729 0.        ]
 [0.         0.00052666 0.        ]
 [0.         0.00071401 0.        ]]


This output is different in that all the negative values had been deleted and replaced with 0's
- thats all there is to the rectified linear activation function

## The Softmax Activation Function

- If we want to switch model to become a classifier (instead of regression), we need to change the output layer activation function
- Softmax Activation Function perfect for multi-class classification problems
- Softmax squashes the output between 0 and 1
- Softmax takes in non-normalized output and returns a probability distribution
- Softmax output represents confidence scores for each class and will add up to 1
- Function: f(x) = e^x / sum(e^x)

### Exponentiation (e^x)

![exponentiation.png](../references/exponential_function.png)

- serves multiple purposes:
1. converts negative values to positive
2. adds stability (more about difference than magnitudes)

In [26]:
layer_outputs = [4.8, 1.21, 2.385]

# e - mathmatical constant, we use E here to match a common coding
# style where constants are uppercase
E = 2.71828182846

# for each value in a vector, calculate the exponential value
exp_values = []
for output in layer_outputs:
    exp_values.append(E**output) # ** - power operator in Python
print(f"Exponentiated Values: \n{exp_values}")

Exponentiated Values: 
[121.51041751893969, 3.3534846525504487, 10.85906266492961]


In [27]:
# now normalize values
norm_base = sum(exp_values) # sum of all exponentiated values
print(f"Sum of Exponentiated Values: {norm_base}")
norm_values = []
for value in exp_values:
    norm_values.append(value / norm_base)
print(f"Normalized Exponentiated Values: \n{norm_values}")
print(f"Sum of Normalized Values: {sum(norm_values)}")

Sum of Exponentiated Values: 135.72296483641975
Normalized Exponentiated Values: 
[0.8952826639573506, 0.024708306782070668, 0.08000902926057876]
Sum of Normalized Values: 1.0


In [28]:
# same operations in Numpy

import numpy as np

# values from the earlier example
layer_outputs = [4.8, 1.21, 2.385]

# for each value in a vector, calculate the exponential value
exp_values = np.exp(layer_outputs)
print(f"Exponentiated Values: {exp_values}")

# now normalize values
norm_values = exp_values / np.sum(exp_values)
print(f"Normalized Exponentiated Values: {norm_values}")
print(f"Sum of Normalized Values: {np.sum(norm_values)}")

Exponentiated Values: [121.51041752   3.35348465  10.85906266]
Normalized Exponentiated Values: [0.89528266 0.02470831 0.08000903]
Sum of Normalized Values: 0.9999999999999999


In [29]:
# training in batches

# get unnormalized probabilities
#exp_values = np.exp(inputs)

# normalize them for each sample
#probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

In [32]:
# we keep the same dimensions as the input

# Softmax Activation
class Activation_Softmax:
    # forward pass
    def forward(self, inputs):
        # get unnormalized probabilities
        exp_values = np.exp(inputs - np.max(inputs,
                                            axis=1,
                                            keepdims=True))
        # normalize them for each sample
        probabilities = exp_values / np.sum(exp_values,
                                            axis=1,
                                            keepdims=True)
        self.output = probabilities

In [33]:
softmax = Activation_Softmax()

softmax.forward([[1, 2, 3]])
print(f"Softmax Output: {softmax.output}")

Softmax Output: [[0.09003057 0.24472847 0.66524096]]


In [34]:
# create dataset
X, y = spiral_data(samples=100, classes=3)

# create dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)

# create ReLU activation (to be used with Dense Layer)
activation1 = Activation_ReLU()

# create second Dense layer with 3 input features (as we take output of previous layer here) and 3 output values
dense2 = Layer_Dense(3, 3)

# create Softmax activation (to be used with Dense Layer)
activation2 = Activation_Softmax()

# make a forward pass of our training data through this layer
dense1.forward(X)

# make a forward pass through activation function
# it takes the output of first dense layer here
activation1.forward(dense1.output)

# make a forward pass through second Dense layer
# it takes outputs of activation function of first layer as inputs
dense2.forward(activation1.output)

# make a forward pass through activation function
# it takes the output of second dense layer here
activation2.forward(dense2.output)

# lets see output of the first few samples:
print(f"Output (No Activation): \n{dense2.output[:5]}")
print(f"Output (Softmax): \n{activation2.output[:5]}")

Output (No Activation): 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Output (Softmax): 
[[0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]]


## Full Code up to this point

In [35]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

# dense layer
class Layer_Dense:
    # layer initialization
    def __init__(self, n_inputs, n_neurons):
        # initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    # forward pass
    def forward(self, inputs):
        # calculate output values from inputs, weights, and biases
        self.output = np.dot(inputs, self.weights) + self.biases
    
class Activation_ReLU:
    # forward pass
    def forward(self, inputs):
        # calculate output values from inputs
        self.output = np.maximum(0, inputs)

class Activation_Softmax:
    # forward pass
    def forward(self, inputs):
        # get unnormalized probabilities
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        # normalize them for each sample
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

# create dataset
X, y = spiral_data(samples=100, classes=3)

# create dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)

# create ReLU activation (to be used with Dense Layer)
activation1 = Activation_ReLU()

# create second Dense layer with 3 input features (as we take output of previous layer here) and 3 output values
dense2 = Layer_Dense(3, 3)

# create Softmax activation (to be used with Dense Layer)
activation2 = Activation_Softmax()

# make a forward pass of our training data through this layer
dense1.forward(X)

# make a forward pass through activation function
# it takes the output of first dense layer here
activation1.forward(dense1.output)

# make a forward pass through second Dense layer
# it takes outputs of activation function of first layer as inputs
dense2.forward(activation1.output)

# make a forward pass through activation function
# it takes the output of second dense layer here
activation2.forward(dense2.output)

# lets see output of the first few samples:
print(f"Output (No Activation): \n{dense2.output[:5]}")
print(f"Output (Softmax): \n{activation2.output[:5]}")

Output (No Activation): 
[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.8183968e-07 -1.5235776e-07  1.2281279e-06]
 [-5.0631292e-07 -4.2422371e-07  3.4195891e-06]
 [-8.4041352e-07 -7.0415609e-07  5.6760728e-06]
 [-1.1393766e-06 -9.5464793e-07  7.6952419e-06]]
Output (Softmax): 
[[0.33333334 0.33333334 0.33333334]
 [0.33333316 0.3333332  0.33333364]
 [0.33333287 0.3333329  0.33333418]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
